service: aws-websocket-chat

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2 # 원하는 리전으로 변경하세요.

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query
        - execute-api:ManageConnections
      Resource: 
        - !GetAtt ConnectionsTable.Arn
        - !GetAtt MessagesTable.Arn
  
  environment:
    CONNECTIONS_TABLE_NAME: !Ref ConnectionsTable
    MESSAGES_TABLE_NAME: !Ref MessagesTable

functions:
  connect:
    handler: src/handlers/connect.handler
    events:
      - websocket: $connect
  disconnect:
    handler: src/handlers/disconnect.handler
    events:
      - websocket: $disconnect
  sendMessage:
    handler: src/handlers/sendMessage.handler
    events:
      - websocket: sendMessage
  joinGroup:
    handler: src/handlers/joinGroup.handler
    events:
      - websocket: joinGroup
  fanoutMessage:
    handler: src/handlers/fanoutMessage.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt MessagesTable.StreamArn

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: GroupIdIndex
            KeySchema:
              - AttributeName: groupId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Messages
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: S
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
