server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092 # Kafka 브로커 주소
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # ChatMessage 객체를 JSON으로 직렬화
      properties:
        spring.json.add.type.headers: false # JSON 직렬화 시 타입 헤더 추가 방지

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379