server:
  port: 9001

#spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:dev}

#---
#spring:
#  config:
#    activate:
#      on-profile: dev

aws:
  dynamodb:
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY:your_aws_access_key}
    secret-key: ${AWS_SECRET_KEY:your_aws_secret_key}

# IAM 권한을 사용하는 경우 별도 accessKey/secretKey 없이도 IRSA나 EC2 역할로 동작합니다.
#aws:
#  region: ap-northeast-2

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#aws:
#  region: ap-northeast-2
