server:
  port: 8082

spring:
  application:
    name: chat-consumer

cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-access-key}
      secret-key: ${AWS_SECRET_KEY:your-secret-key}
    dynamodb:
      endpoint: ${AWS_DYNAMODB_ENDPOINT:http://localhost}:8000 # For local DynamoDB, remove for AWS
      tableName: ChatMessage