spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092 # Kafka 브로커 주소
    consumer:
      group-id: chat-consumer-group # 컨슈머 그룹 ID
      auto-offset-reset: earliest # 오프셋 리셋 정책
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # JSON 메시지를 ChatMessage 객체로 역직렬화
      properties:
        spring.json.trusted.packages: "com.nameless.social.core.entity" # JSON 역직렬화 시 신뢰할 패키지 지정

  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/social_chat
    username: ${DB_USER:root}
    #    password: ${DB_PASSWORD:password}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

jpa.auditing:
  enabled: true
