spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/social_chat
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://cognito-idp.{region}.amazonaws.com/{userPoolId} # Replace with your Cognito User Pool Issuer URI
#          jwk-set-uri: https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json # Replace with your Cognito User Pool JWKS URI

jpa.auditing:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
