spring:
  user-datasource:
    url: jdbc:mariadb://${USER_DB_HOST:localhost}:3306/social_user
    username: ${USER_DB_USER:root}
    password: ${USER_DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  chat-datasource:
    url: jdbc:mariadb://${CHAT_DB_HOST:localhost}:3306/social_chat
    username: ${CHAT_DB_USER:root}
    password: ${CHAT_DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  user:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

chat:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://cognito-idp.{region}.amazonaws.com/{userPoolId} # Replace with your Cognito User Pool Issuer URI
#          jwk-set-uri: https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json # Replace with your Cognito User Pool JWKS URI

jpa.auditing:
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
